### ISSUE TITLE
Selenium download server not found

### ISSUE THREAD

**Issue by markn86** [FMCorz/mdk#117]
Ah Belge, where do I start? This software is amazing and has improved my life drastically. You sir, are a living legend.

Anyways, here is the output of the command. Please fix.

BTW, rubbish bug, don't do again.

<3

mark@mma:~/htdocs/sm$ mdk behat --selenium-download
Attempting to find a download for Selenium
Could not locate Selenium server to download

**Comment by merrill-oakland** [comment]
Yeah, I'm seeing the same thing.

**Comment by FMCorz** [comment]
They changed the filename on the website, hence MDK does not find it any more.

https://github.com/FMCorz/mdk/blob/master/mdk/commands/behat.py#L194

As a workaround, manually download the file and place it here:

    echo $(mdk config show dirs.mdk)/selenium.jar

**Comment by FMCorz** [comment]
To fix this:

Consider using the NPM package for this (webdriver-manager), or rip off their code:

https://github.com/angular/protractor/blob/master/bin/webdriver-manager

**Comment by markn86** [comment]
Why not simply change the URL in mdk?

**Comment by FMCorz** [comment]
I think it changes as it's a minified URL.

**Comment by FMCorz** [comment]
Fixed in #128.
