### ISSUE TITLE
I am unable to use `mdk rebase`

### ISSUE THREAD

**Issue by mudrd8mz** [FMCorz/mdk#133]
I must admit I am failing to use `mdk rebase`.

The first issue was that it took me a while to actually learn that I have to run it like

    mdk rebase --issues=MDL-12345 m30

because without using the `=` (which is what the --help suggests) the issue number is considered as positional argument. So the help might be improved.

The other issue is that I seem unable to make this mdk-rebase work with my branches. I always use that "suffix" so my branches are named like "MDL-12345-30-something". But when I pass the issue number to mdk-rebase, it assumes the branch name without the suffix.

**Comment by FMCorz** [comment]
Hi David,

It's been years that I am tempted to remove this command but some developers seem to be using it. I don't.

About `--issues`, I think you don't need to pass `MDL-` at all.
About the suffix, have you tried with `--suffix`?

Cheers,
Fred

**Comment by mudrd8mz** [comment]
>  I am tempted to remove this command

Yeah, I understand that. I also found rebasing via vanilla git more effective at the end.

> have you tried with --suffix

Ouch, my bad. Sorry I did not notice that in the help. You are right, it is there.

Anyway, I am closing this issue now as I don't see much of point of working on this. Thanks for your help Fred.
