### ISSUE TITLE
mdk behat does not download the most recent selenium version

### ISSUE THREAD

**Issue by mudrd8mz** [FMCorz/mdk#190]
As per https://www.seleniumhq.org/download/ and https://docs.moodle.org/dev/Acceptance_testing/Browsers/Working_combinations_of_OS%2BBrowser%2Bselenium we want to use the latest selenium 3.141.59 now.

However, when running `mdk behat --selenium-download` the version 3.9.1 is downloaded.

I suspect that is because how
```
matches = sorted(re.findall(r'[a-z0-9/._-]+selenium-server-standalone-[0-9.]+\.jar', content, re.I))
```
in `behat.py` sorts the versions and I think that 3.9.1 is evaluated as higher than 3.141.59  ?

**Comment by FMCorz** [comment]
Thanks for the report David.
