### ISSUE TITLE
TypeError when downloading patch file - Python 3.7.3

### ISSUE THREAD

**Issue by snake** [FMCorz/mdk#195]
Using "mdk pull ISSUE_NUM" try to pull a patch file from a security issue. When prompted, select the number of the patch file.
See the error: "TypeError: write() argument must be str, not bytes"

**Comment by FMCorz** [comment]
Probably related to the switch to Python 3, I imagine this is the incriminating line: https://github.com/FMCorz/mdk/blob/3fa84c41dbdde0c08d1e8d152ffd929f73c8548e/mdk/jira.py#L112

**Comment by FMCorz** [comment]
Never mind, did not notice the pull request.
