### ISSUE TITLE
error on ubuntu 18.04 when running init

### ISSUE THREAD

**Issue by firecentaur** [FMCorz/mdk#204]
Hi there, I am getting this error when running python mdk.py init

What user are you initialising MDK for? [fire]
 
SyntaxError: unexpected EOF while parsing (<string>, line 0)

**Comment by FMCorz** [comment]
Hi @firecentaur,

Thanks for the report. Would you happen to have an existing and maybe corrupted config file at `~/.moodle-sdk/config.json`?

**Comment by FMCorz** [comment]
Hi @firecentaur,

I came across this error myself. This is likely due to using the wrong version of Python.
Please make sure that MDK is installed and invoked using Python 3.
