### ISSUE TITLE
Merge failed after executing mdk pull

### ISSUE THREAD

**Issue by meirzamoodle** [FMCorz/mdk#214]
Hi.

I work on Ubuntu, merge failed error happens every time pulling with MDK command below

```
▶ mdk pull MDL-1234 -t
...
Merging into current branch
FetchException: Merge failed, resolve the conflicts and commit
```

**Comment by FMCorz** [comment]
MDK cannot resolve git merges on its own. Once this command fails your repository will be in an unmerged state, you either need to manually abort the merge `git merge --abort` or resolve its conflicts manually.

**Comment by meirzamoodle** [comment]
The problem is there is no information on which files that conflicted

**Comment by FMCorz** [comment]
I'm afraid this is beyond the scope of what MDK can do. I'd suggest starting with `git status`.
