### ISSUE TITLE
Bad chmod of config.php causing PHP Fatal error in version 2.1.2

### ISSUE THREAD

**Issue by snake** [FMCorz/mdk#239]
Debian 12. Updated mdk. PHP 8.1. Have tested this for a few versions (4.5, main). 

Install using:
mdk create -v main -i
or 
mdk create -v 405 -i

Site installs fine (at least seems to based on CLI output), but accessing the site results in a 500, and apache logs show:
PHP Fatal error:  Uncaught Error: Failed opening required '../config.php' (include_path='.:/usr/share/php') in /home/snake/moodledata/testing/moodle/login/index.php:27

Looks like this commit causes a bad chmod of config.php.
https://github.com/FMCorz/mdk/commit/16916f43542d7e1230e1691451b3b60ceb04f3a6#diff-1a5614e0a1c7856333a65d0cb07a7a486634d26172635123b67e6cb8f84c27a5L510

It results in a 640 chmod rather than a 666 now on my system (666 being what all sites prior to this change would get). 

Reverting that commit resolves this.

**Comment by FMCorz** [comment]
Hi @snake,

Thanks for reporting this. I spotted something that could be related, could you try with the above commit? Thanks!

**Comment by snake** [comment]
Confirming the above commit resolves the issue, at least on my system. 

@junpataleta (on Ubuntu) reports he didn't have quite the same fatal error as I did with the original change, so maybe he can also test this recent commit out?

**Comment by junpataleta** [comment]
Yep, I can confirm this works okay. Thanks, Fred!

**Comment by FMCorz** [comment]
Thank you both!
